# Generated by Django 5.1.3 on 2024-11-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('dui_nit', models.CharField(max_length=20)),
                ('oferta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehiculo', models.CharField(max_length=100)),
                ('id_vehicular', models.CharField(max_length=50)),
                ('kilometraje', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('dui_nit', 'correo')},
            },
        ),
    ]
