# Generated by Django 5.1.3 on 2024-11-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_subastas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oferta',
            unique_together=set(),
        ),
    ]
