# Generated by Django 5.1.3 on 2024-11-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_subastas', '0003_rename_vehiculo_oferta_vehículo'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='teléfono',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='dui_nit',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='oferta',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='vehículo',
            field=models.CharField(max_length=50),
        ),
    ]
