# Generated by Django 5.1.3 on 2024-11-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_subastas', '0004_oferta_teléfono_alter_oferta_dui_nit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='vehículo',
            new_name='artículo',
        ),
    ]
